#!/bin/bash
# SINTAX : install-migasfree-server <DISTRO> <BRANCH>

_DISTRO=$1
_BRANCH=$2
_PMS=""

function check_pkgs {
    oIFS=$IFS
    IFS=" "
    _PACKAGES=$1
    if [ $_PMS == "deb" ] ; then
        _CMD="dpkg -l"
    else
        _CMD="rpm -q"
    fi
    for i in $_PACKAGES
    do
        $_CMD $i
        if [ $? -gt 0 ] ; then
            echo "$i is not installed"
            echo "packages needed: $_PACKAGES"
            IFS=$oIFS
            exit 3
        fi
    done
    IFS=$oIFS
}

function create_package {
    local _PROJECT=$1
    local _BRANCH=$2
    git clone https://github.com/agacias/$_PROJECT.git
    cd $_PROJECT
    git checkout $_BRANCH
    if [ $_PMS == "deb" ] ; then
        ln -s stdeb.cfg.$_DISTRO stdeb.cfg
        python setup.py --command-packages=stdeb.command bdist_deb
        cp deb_dist/*.deb ..
    else
        ln -s setup.cfg.$_DISTRO setup.cfg
        python setup.py bdist_rpm
        cp  dist/*.rpm ..
    fi
    cd ..
    #rm -rf $_PROJECT
}

function install_packages {
    if [ $_PMS == "deb" ] ; then
        dpkg -i *.deb
        apt-get install -f
    else
        rpm -ivh *.rpm
    fi
}


# CHECK PARAMETERS
# ================
if [ -z $_DISTRO ] ; then
    echo "DISTRO not specified"
    exit 1
fi

if [ -z $_BRANCH ] ; then
    echo "BRANCH not specified"
    exit 2
fi


# GET PMS
if [ $_DISTRO == "debian" ] ; then
    _PMS="deb"
else
    _PMS="rpm"
fi


# CHECK PACKAGES NECESSARIES FOR SETUP.PY
# =======================================
if [ $_PMS == "deb" ] ; then
    check_pkgs "git python python-stdeb python-setuptools"
else
    check_pkgs "git python python-setuptools"
fi


# CREATE PACKAGES
# ==============
create_package "migasfree" $_BRANCH
create_package "django-ajax-selects" "master"


# INSTALL PACKAGES
# ================
install_packages


# CREATE APLICATION MIGASFREE
# ===========================
migasfree-server-from-scratch


