#!/bin/bash
# Create messages in a languaje
# sintax: make_po <LANGUAGE>
# example: ./make_po es

_LANG=$1

if [ -z $_LANG ]; then
  echo "Error. Language not especified."
  echo "  Sintax: make_po <LANGUAJE>"
  echo "  Sample: ./make_po es"
  exit 1
fi

cd /srv/Django/migasfree
if [ -e locale ] ;then
  django-admin.py makemessages --all
  nano locale/$_LANG/LC_MESSAGES/django.po
  django-admin.py compilemessages
else
  mkdir locale
  django-admin.py makemessages --locale=$_LANG
  nano locale/$_LANG/LC_MESSAGES/django.po
  django-admin.py compilemessages
fi
chown -R www-data locale

