#!/bin/sh

# migrate DB with south
cd /
cd $(python -c "import migasfree;print migasfree.__path__[0]")
python manage.py schemamigration server --auto --settings=migasfree.settings.production || :
python manage.py migrate server --settings=migasfree.settings.production || :

migasfree-server-config-webserver
