# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'intended', 'Intended'), (b'reserved', 'Reserved'), (b'unknown', 'Unknown'), (b'in repair', 'In repair'), (b'available', 'Available'), (b'unsubscribed', 'Unsubscribed')], default=b'intended', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'verbose_name': 'Status Log',
                'verbose_name_plural': 'Status Logs',
                'permissions': (('can_save_statuslog', 'Can save Status Log'),),
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[(b'intended', 'Intended'), (b'reserved', 'Reserved'), (b'unknown', 'Unknown'), (b'in repair', 'In repair'), (b'available', 'Available'), (b'unsubscribed', 'Unsubscribed')], default=b'intended', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='attributeset',
            name='attributes',
            field=models.ManyToManyField(blank=True, help_text='Assigned Attributes', to='server.Attribute', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='attributeset',
            name='excludes',
            field=models.ManyToManyField(blank=True, help_text='Excluded Attributes', related_name='ExcludeAttributeGroup', to='server.Attribute', verbose_name='excludes'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='dateinput',
            field=models.DateField(auto_now_add=True, help_text='Date of input of Computer in migasfree system', verbose_name='date input'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='devices_logical',
            field=models.ManyToManyField(blank=True, to='server.DeviceLogical', verbose_name='devices'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='server.Attribute', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='connections',
            field=models.ManyToManyField(blank=True, to='server.DeviceConnection', verbose_name='connections'),
        ),
        migrations.AlterField(
            model_name='error',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='fault',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='faultdef',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='server.Attribute', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='faultdef',
            name='users',
            field=models.ManyToManyField(blank=True, to='server.UserProfile', verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='hwnode',
            name='level',
            field=models.IntegerField(verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='login',
            name='attributes',
            field=models.ManyToManyField(blank=True, help_text='Sent attributes', to='server.Attribute', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='login',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='computer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.Computer', verbose_name='computer'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='migration',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='query',
            name='code',
            field=models.TextField(blank=True, default=b"query=Package.objects.filter(version=VERSION).filter(Q(repository__id__exact=None))\nfields=('id','name','store__name')\ntitles=('id','name','store')", help_text='Django Code: version=user.version, query=QuerySet, fields=list of QuerySet fields names to show, titles=list of QuerySet fields titles', null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='query',
            name='parameters',
            field=models.TextField(blank=True, help_text='Django Code', null=True, verbose_name='parameters'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='attributes',
            field=models.ManyToManyField(blank=True, help_text='Assigned Attributes', to='server.Attribute', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='excludes',
            field=models.ManyToManyField(blank=True, help_text='Excluded Attributes', related_name='ExcludeAttribute', to='server.Attribute', verbose_name='excludes'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='packages',
            field=models.ManyToManyField(blank=True, help_text='Assigned Packages', to='server.Package', verbose_name='Packages/Set'),
        ),
        migrations.AlterField(
            model_name='scheduledelay',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='server.Attribute', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='statuslog',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Computer', verbose_name='computer'),
        ),
    ]
