# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_4_9_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelogical',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
    ]
