# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-20 14:25
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_4_14_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update',
            new_name='Synchronization'
        ),
        migrations.RenameField(
            model_name='synchronization',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='synchronization',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='synchronization',
            options={
                'permissions': (('can_save_synchronization', 'Can save Synchronization'),),
                'verbose_name': 'Synchronization',
                'verbose_name_plural': 'Synchronizations'
            },
        ),
    ]
