# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-03 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_4_14_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name='date',
            ),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(
                verbose_name='message',
            ),
        ),
    ]
