# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_4_14_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaultDef',
            new_name='FaultDefinition'
        ),
        migrations.RenameField(
            model_name='FaultDefinition',
            old_name='active',
            new_name='enabled',
        ),
        migrations.RenameField(
            model_name='FaultDefinition',
            old_name='attributes',
            new_name='included_attributes',
        ),
        migrations.AlterField(
            model_name='FaultDefinition',
            name='language',
            field=models.IntegerField(
                choices=[(0, b'bash'), (1, b'python'), (2, b'perl'), (3, b'php'), (4, b'ruby'), (5, b'cmd')],
                default=0,
                verbose_name='programming language'
            )
        ),
        migrations.AlterField(
            model_name='FaultDefinition',
            name='included_attributes',
            field=models.ManyToManyField(
                to='server.Attribute',
                verbose_name='included attributes', blank=True,
            ),
        ),
        migrations.AddField(
            model_name='FaultDefinition',
            name='excluded_attributes',
            field=models.ManyToManyField(
                to='server.Attribute',
                verbose_name='excluded attributes', blank=True,
                related_name="ExcludeAttributeFaultDefinition",
            ),
        ),
        migrations.AlterField(
            model_name='fault',
            name='fault_definition',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='server.FaultDefinition',
                verbose_name='fault definition'
            ),
        ),
        migrations.AlterModelOptions(
            name='FaultDefinition',
            options={
                'ordering': ['name'],
                'permissions': (('can_save_faultdefinition', 'Can save Fault Definition'),),
                'verbose_name': 'Fault Definition',
                'verbose_name_plural': 'Fault Definitions'
            },
        ),
        migrations.AlterField(
            model_name='FaultDefinition',
            name='code',
            field=models.TextField(blank=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='FaultDefinition',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='property',
            name='language',
            field=models.IntegerField(
                choices=[(0, b'bash'), (1, b'python'), (2, b'perl'), (3, b'php'), (4, b'ruby'), (5, b'cmd')],
                default=0,
                verbose_name='programming language'
            ),
        ),
    ]
