# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import migasfree.server.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_4_16_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('excluded_attributes', models.ManyToManyField(blank=True, related_name='DomainExcludedAttribute', to='server.Attribute', verbose_name='excluded attributes')),
                ('included_attributes', models.ManyToManyField(blank=True, related_name='DomainIncludedAttribute', to='server.Attribute', verbose_name='included attributes')),
                ('tags', models.ManyToManyField(blank=True, related_name='domain_tags', to='server.ServerAttribute', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'permissions': (('can_save_domain', 'Can save Domain'),),
            },
            bases=(models.Model, migasfree.server.models.common.MigasLink),
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Domain', verbose_name='domain')),
                ('excluded_attributes', models.ManyToManyField(blank=True, related_name='ScopeExcludedAttribute', to='server.Attribute', verbose_name='excluded attributes')),
                ('included_attributes', models.ManyToManyField(blank=True, related_name='ScopeIncludedAttribute', to='server.Attribute', verbose_name='included attributes')),
            ],
            options={
                'verbose_name': 'Scope',
                'verbose_name_plural': 'Scopes',
                'permissions': (('can_save_scope', 'Can save Scope'),),
            },
            bases=(models.Model, migasfree.server.models.common.MigasLink),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='project',
        ),
        migrations.AddField(
            model_name='scope',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.UserProfile', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Domain', verbose_name='domain'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='domain_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Domain', verbose_name='domain'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='domains', to='server.Domain', verbose_name='domains'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scope_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.Scope', verbose_name='Scope'),
        ),
    ]
